FROM node:22.14.0 AS source
WORKDIR /app
COPY . .
RUN yarn install
RUN yarn build
RUN ls -a

FROM node:22.14.0-slim AS runner
WORKDIR /app
COPY --from=source app/.next ./.next
COPY --from=source app/package.json ./
COPY --from=source app/.npmrc ./
RUN ls -a
RUN yarn install --production
EXPOSE 3000
CMD [ "yarn","start" ]

