name: Prod Release
on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dmsconnect"
      - name: Setup Dopler CLI
        run: curl -sLf --retry 3 --retry-delay 2 https://cli.doppler.com/install.sh | sudo sh
      - name: Install dependencies
        run: yarn install
      - name: Publish packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish:ci
      - name: Download Environment Variables
        run: doppler secrets download --no-file --format env > .env
        env:
          DOPPLER_TOKEN: ${{secrets.DOPPLER_TOKEN}}
      - name: Build Image
        run: |
          docker build . -t dmsconnect-webapp -f ./docker/webapp
